name: Reusable 97 Docker Smoke

on:
  workflow_call:
    inputs:
      debug-build:
        description: Enable verbose test output for debugging
        required: false
        default: false
        type: boolean

jobs:
  docker-smoke:
    name: docker-smoke
    uses: ./.github/workflows/pr-12-docker-smoke.yml
    with:
      debug_build: ${{ inputs['debug-build'] }}
